# Copyright (C) 2025 Dan Novischi. All rights reserved.
# This software may be modified and distributed under the terms of the
# GNU Lesser General Public License v3 or any later version.

/**:
  ros__parameters:
    # RDrive is the Antrobot navigation module. The moudle implements the control system 
    # for the differential drive in a closed loop fashion
    rdrive:
      wheel_radius: 0.03  # Radius of the wheels in meters
      wheel_separation: 0.215  # Distance between the wheels in meters
      encoder_cpr_left: 2940  # Encoder counts per revolution for the left motor
      encoder_cpr_right: 2940  # Encoder counts per revolution for the right motor

    # RPLidar is the lidar used for Antrobot, which currently integrates A1 and A2
    rplidar:
      serial_port: "/dev/ttyUSB0"  # Serial port for the RPLIDAR device
      serial_baudrate: 115200  # Baud rate for the RPLIDAR serial communication
      frame_id: "antrobot1_laser_link"  # Frame ID for the laser scan data
      inverted: false  # Whether the laser scan data is inverted
      angle_compensate: true  # Whether to use angle compensation for the laser scan
      scan_mode: "Sensitivity"  # Scan mode for the RPLIDAR (Options: "Standard", "Express", "Boost", "Sensitivity")

    # The static tf defines the structural frames for the components of the Antrobot as extracted from the mechanical design
    tf_static:
      transforms:
        - parent_frame: "base_footprint"  # base_footprint is the frame at ground level, at robot center
          child_frame: "base_link" # base_link is the frame at the wheel base
          translation: [0.0, 0.0, 0.03995]  # base_link (wheel_base) is 0.03995m above base_footprint (at ground level)
          rotation: [0.0, 0.0, 0.0] # no rotation
        - parent_frame: "base_link" # base_link is the frame at the wheel base
          child_frame: "laser_link" # laser_link is the frame at the lidar
          translation: [0.0, 0.0, 0.19295]  # laser (Lidar A1 link) is 0.19295m above base_link (wheel_base)
          # translation: [0.0, 0.0, 0.1907]  # laser (Lidar A2 link) is 0.1907m above base_link (wheel_base), when using 10mm spacer
          rotation: [0.0, 0.0, 0.0]

    # Cartographer is another SLAM algorithm used for mapping and localization
    cartographer:
      config_file: 'antrobot_cartographer_2d.lua' # Name of the Cartographer configuration file
      resolution: 0.05  # Resolution of the occupancy grid in meters
      publish_period_sec: 1.0  # Publishing period for the occupancy grid node in seconds




